name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.22.2]  # Specify the Go version you want to use

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -o SimpleChat

      - name: Run tests
        run: go test ./...  # Run all tests in the project

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SimpleChat
          path: SimpleChat  # Specify the output file or directory to be uploaded
