name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.22.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -o SimpleChat-${{ matrix.os }}  # Include OS in the executable name

      - name: Run tests
        run: go test ./...

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SimpleChat-${{ matrix.os }}  # Unique artifact name for each OS
          path: SimpleChat-${{ matrix.os }}  # Ensure this points to the correct executable
